Switch doma manifest to Android BSP v1.2.0
xen-troops/manifests pull request #13
Opened 2017-11-01 18:26 UTC by arminn

- Set default branch for epam projects to android-bsp-v1.2.0
- Add LLVM and CLANG projects related to DDK 1.9
- Switch device/renesas/salvator, device/renesas/kernel
to android-bsp-v1.2.0-ces2018 branch

Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

2017-11-01 19:12 UTC, andr2000 requested changes
imo, these changes are 2 different commits
NACK

2017-11-02 10:07 UTC, arminn commented
Split to 2 commits, plz review

2017-11-02 10:24 UTC, iartemenko commented
lgtm

2017-11-02 14:58 UTC, aanisov approved these changes

2017-11-02 15:20 UTC, andr2000 commented
lgtm, rb

2017-11-02 15:40 UTC, merged